version: "3.7"

services:
  ahoy_dtu:
    image: ahoy_weather:0.6.10.3
    container_name: ahoy_weather
    working_dir: "/"
    volumes:
      - type: bind
        source: /mnt/usb_hdd/python_playground/NRF_container/Ahoy
        target: /ahoy_work
    privileged: true
    restart: always
    environment:
      TZ: Europe/Berlin
    deploy:
      resources:
          limits:
            cpus: "1.0"
            memory: 512M