version: "3.7"

services:
  ahoy_dtu:
    image: ahoy:0.6.1
    container_name: ahoy_weather
    working_dir: "/ahoy"
    volumes:
      - type: bind
        source: /mnt/usb_hdd/python_playground/NRF_container/Ahoy
        target: /ahoy_work
    privileged: true
    restart: always
    environment:
      TZ: Europe/Berlin