version: "3.7"

services:
  ahoy_dtu:
    image: ahoy_dtu
    container_name: ahoy_dtu
    working_dir: /ahoy
    volumes:
      - type: bind
        source: /mnt/usb_hdd/python_playground/ahoy_container
        target: /ahoy_work
    privileged: true
    restart: always
    environment:
      TZ: Europe/Berlin